import React from 'react'
import Header from '../../components/Header/Header'
import Footer from '../../components/Footer/Footer'
import SubHeader from '../../components/Header/SubHeader'
function TermsAndConditions() {
  return (
    <div>
        <Header />
<SubHeader />
        <div className="container TermsAndConditions">
            <h1 className="my-4 center">Terms and Conditions</h1>

            <p className="l2">
            Welcome To HELLOMITR!
            </p>

            <p className="l2">
            The portal www.hellomitr.com and its corresponding mobile application (collectively, “HELLOMITR ”), is managed and operated by Hellomitr Technology Pvt Ltd (“ HMPL”, “we”, “us” or “our”). Any natural or legal person who accesses and/or uses Hellomitr in any manner (“you” or “your”) or uses any current or future service or functionality or offer made available on Hellomitr (“Service”) will be subject to these terms and conditions for use of Hellomitr (“Terms of Use”), as updated from time to time and such terms, guidelines and conditions as may be applicable to such Service (“Service Terms”). If these Terms of Use are inconsistent with such Service Terms, the Service Terms will control to the extent of such inconsistency with respect to the applicable Service.
            </p>

            <p className="l2">
            These Terms of Use constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures. Please read these Terms of Use carefully before using or accessing Hellomitr or availing any Service. By using the Hellomitr or availing any Service, you signify your agreement to be bound by these Terms of Use.
            </p>

            {/* <p className="l2">Following terms of use are subject to apply :</p>

            <ul>
                <li className="l2">The content of the pages of this website is for your general information and use only. It is subject to change without notice.</li>
                <li className="l2">Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
                <li className="l2">Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products or information available through this website meet your specific requirements.</li>
                <li className="l2">This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</li>
                <li className="l2">All trademarks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website.</li>
                <li className="l2">Unauthorized use of this website may give rise to a claim for damages and/or be a criminal offence.</li>
                <li className="l2">From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</li>
                <li className="l2">You may not create a link to this website from another website or document without Hellomitr Technology Private Limited prior written consent.</li>
                <li className="l2">Your use of this website and any dispute arising out of such use of the website is subject to the laws of India  or other regulatory authority.</li>

            </ul>

            <p className="l2">Unless otherwise agreed in writing with Hellomitr Technology Private Limited, As per your agreement with Hellomitr Technology Private Limited will always include, at a minimum, the terms and conditions set out in this document. These are referred to below as the general terms.</p> */}

            <h5>1. USE OF HELLOMITR:</h5>
            <p className="l2">You agree and acknowledge that Hellomitr is an online platform that enables you to purchase the products listed on Hellomitr at the indicated price at any time from the serviceable locations. Except where we are the seller of the relevant product on Hellomitr, you agree and acknowledge that we are only a facilitator and are not and cannot be a party to or control in any manner any transactions on Hellomitr. Accordingly, such contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on Hellomitr.</p>

            <h5>2. ELIGIBILITY:</h5>
            <p className="l2">Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e. persons who are 18 years of age or older, are of sound mind, and are not disqualified from entering into contracts by any law, can use and access Hellomitr. If you are a minor i.e. under the age of 18 years, you may use Hellomitr only with the involvement of a parent or guardian.</p>
            {/* <p className="l2">You may not use the services and may not accept the terms if,</p>
            <p className="l2">(a) you are not of legal age to form a binding contract with ‘us’, or</p>
            <p className="l2">(b) you are a person barred from receiving the services under the laws of India.</p> */}

            <h5>3. REGISTRATION AND OPERATION OF YOUR ACCOUNT:</h5>
            <ul>
                <li className="l2">
                3.1. In order to use Hellomitr and avail the Services, you will have to register on Hellomitr. Registration is a one-time process and is free of cost. You may register in one of the following ways:
                </li>
                <li className="l2">3.1.1. By creating a Hellomitr account: You can register by providing relevant information, such as your name, gender, and such other details relevant for creating an account. Your login ID and password will be created basis the information provided by you, which you can use to access your Hellomitr account at any time.</li>
                <li className="l2">3.1.2. By using a third-party account: You may use the login credentials from any third-party accounts maintained by you, as identified by Hellomitr (for example, Google or Facebook). If you use such third party account, you will also be subject to specific terms and conditions applicable to such account, as may be imposed by the relevant third-party.</li>
                <li className="l2"> Your credentials shared by you at the time of registration and your Hellomitr login ID and password are referred to as “Account Information”.</li>
                <li className="l2">3.2. You are solely authorized to operate the account created by you. Consequently, it is your responsibility to maintain the confidentiality of the Account Information and for restricting access to your computer/mobile/other similar devices to prevent unauthorized access to your account. You will at all times keep your Account Information current and accurate. You can access and update much of the Account Information you provided us with in the ‘Your Account’ area of the website.</li>
                <li className="l2">3.3. You will: (a) immediately inform Hellomitr of any unauthorized use of the account or any other security breach; and (b) ensure that you log out of your account at the end of each session. Hellomitr will not be liable for any loss or direct or indirect damage arising from your failure to comply with these Terms of Use. You may be held liable for any losses incurred to Hellomitr or any other user due to unauthorized use of their account, resulting from your failure to keep your Account Information safe, secure and confidential. We reserve the right to refuse access to Hellomitr, terminate accounts, remove or edit content at any time without notice to you.</li>
            </ul>

            <h5>4. COMMUNICATION AND UNSUBSCRIPTION:</h5>
            <ul>
                <li className="l2">4.1. You understand that once you have shared your Account Information and successfully registered on Hellomitr, you may receive SMS or email notifications from Hellomitr relating to your registration and transactions on Hellomitr.</li>
                <li className="l2">4.2. You may also receive such notifications regarding any marketing / promotional activities that maybe available on Hellomitr from time to time. By sharing your Account Information and registering on Hellomitr and/ or verifying your contact number with us, you explicitly consent to receive marketing/ promotional communications (through call, SMS, email or other digital and electronic means) from us and/or our authorized representatives regarding any new services or offerings, even if your contact number is registered under the DND/NCPR list under the Telecom Commercial Communications Customer Preference Regulations, 2018.</li>
                <li className="l2">4.3. Hellomitr may also send notifications and reminders with respect to the Services on Hellomitr. While Hellomitr endeavors to provide these notifications and reminders to you promptly, Hellomitr does not provide any guarantee and will not be held liable or responsible for any failure to send such notifications/reminders to you.</li>
                <li className="l2">4.4. You can unsubscribe / opt-out from receiving marketing/ promotional communications, newsletters and other notifications from Hellomitr at any time by following the instructions set out in such communications.</li>
            </ul>

            <h5>5. LICENSE AND ACCESS TO PLATFORM</h5>
            <p className="l2">5.1. Your use of Hellomitr, the Services, and access to the Hellomitr Content ( as defined below) is subject to a limited, revocable and non-exclusive license which is granted to you when you register on Hellomitr. You will use Hellomitr solely for identifying products, carrying out purchases of products and processing returns and refunds, in accordance with Return and Refund Policy, for your personal use only and not for business purposes.</p>
            <p className="l2">5.2. The license granted to you does not include a license for: (a) resale of Products or commercial use of Hellomitr or Hellomitr Content, (b) any collection and use of product listings, description, or prices, (c) any use of Hellomitr, the Services and/or of Hellomitr Content other than as contemplated in these Terms of Use, (d) any downloading or copying of Account Information, (e) any use of data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) any parts of Hellomitr, (e) creating and/ or publishing your own database that features parts of Hellomitr.</p>
            <p className="l2">5.3. You grant to Hellomitr a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on any material posted by you on Hellomitr without additional approval or consideration in any form, media, or technology now known or later developed, for the full term of any rights that may exist in such content, and you waive any claim over all feedback, comments, ideas or suggestions or any other content provided through or on Hellomitr. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Hellomitr, including the execution of deeds and documents, at its request.</p>
            <p className="l2">Please note that Hellomitr at all times reserves the right to refuse your access to Hellomitr, terminate/deactivate your account, remove or edit content on Hellomitr, at its discretion.</p>

            <h5>6. PERSONAL INFORMATION PRIVACY:</h5>
            <p className="l2">6.1. During the course of your registration on and usage of Hellomitr or availing the Services, Hellomitr may collect and store and/or you may provide us with, personal identifiable and sensitive information about you, including without limitation your name, phone number, email address, address, postal code, occupation, login details etc.</p>
            <p className="l2">6.2. Hellomitr respects the sensitivity of the information about you and we appreciate your trust in us. In this regard, Hellomitr has formulated the Privacy Policy, which shall be deemed to be included in these Terms of Use, setting out the manner in which your information is collected, stored, processed, used and disclosed. If you object terms of our Privacy Policy, please do not use or access Hellomitr or avail the Services. For more information, please refer to the Privacy Policy.</p>

            <h5>7. CONTENT ON PLATFORM:</h5>
            <p className="l2">7.1. All information, content, material, text, graphics, images, logos, button icons, software code, interface, design and the collection, arrangement and assembly of the content on Hellomitr or any of the other Services are the property of Hellomitr or its affiliates (“Hellomitr Content”), and are protected under copyright, trademark and other applicable laws. Further, all trademarks, services marks, trade names and trade secrets in relation to Hellomitr whether or not displayed on Hellomitr, are proprietary to Hellomitr.</p>
            <p className="l2">7.2. Hellomitr may display on Hellomitr any third-party logos, trade names, trademarks of other brands, as per the license granted to Hellomitr by such brands.</p>
            <p className="l2">7.3. No information, content or material from Hellomitr (including the Hellomitr Content) may be copied, reproduced, republished, duplicated, copied, sold, resold, uploaded, posted, transmitted, distributed or otherwise exploited in any way (including for any commercial purpose) without Hellomitr’s express written permission. You will not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Hellomitr and its affiliates without express written consent. You may not use any meta tags or any other “hidden text” utilizing Hellomitr’s or its affiliates’ names or trademarks without the express written consent of Hellomitr and/or its affiliates, as applicable. Any unauthorized use terminates the permissions granted in these Terms of Use.</p>

            <h5>8. DISCLAIMERS:</h5>
            <p className="l2">8.1. Hellomitr will try to make access to and use of Hellomitr error-free and without interruptions. However, your access to Hellomitr may be occasionally suspended or restricted to allow for repairs, maintenance, or for introduction of new facilities or services on Hellomitr. Hellomitr does not take responsibility for any access or usage problems that arise from internet related issues at your end.</p>
            <p className="l2">8.2. All information in relation to third parties, including sellers and the products listed by them on Hellomitr (“Third Party Information”) are provided only for reference. Hellomitr, in its capacity of an intermediary under the applicable laws, is not endorsing Third Party Information and is not responsible for any errors and representation nor is it associated with it and you shall access the Third Party Information at your own risk.</p>
            <p className="l2">8.3. Hellomitr may contain user generated content which Hellomitr does not pre-screen and which contains views that may be opinions of users/ experts. Hellomitr will do its best to monitor, edit or remove such user generated content where it is necessary to do so (for instance, if such content violates these Terms of Use). Hellomitr does not promise that the user generated content on Hellomitr is accurate, complete or updated, that it will not offend or upset any person or that it does not infringe the intellectual property rights of third parties.</p>
            <p className="l2">8.4. To help you in identifying the products of your choice, description of the products are provided on Hellomitr by the relevant seller through photographs, videos, charts, screenshots, infographics and other visual aids. While reasonable efforts are made to provide accurate visual representations, the appearance/color of the products when delivered may differ for various reasons.</p>
            <p className="l2">8.5. The Services included on Hellomitr are provided on an “as is” and “as available” basis without any representations or warranties, express or implied, except as otherwise specified in writing. Hellomitr does not covenant or provide any representations and warranties:</p>
            <p className="l2">8.5.1. in respect of quality, suitability, accuracy, reliability, performance, safety, merchantability, fitness for a particular purpose/consumption or the content (including product or pricing information and/or specifications) on Hellomitr;</p>
            <p className="l2">8.5.2. That the Services will be made available at all times;</p>
            <p className="l2">8.5.3. that the operation of Hellomitr, including the functions contained in any content, information and materials on Hellomitr or any third-party sites or services linked to Hellomitr will be uninterrupted, or that the defects will be rectified, or that Hellomitr or the servers that make such content, information and materials available are free of viruses or other harmful components; and</p>
            <p className="l2">8.5.4. That the Hellomitr Content available on Hellomitr is complete, true, accurate or non-misleading.</p>
            <p className="l2">8.6. Parties other than Hellomitr and its affiliates may operate stores, provide services, or list or sell product lines on Hellomitr. We are not responsible for examining or evaluating, and we do not warrant or endorse the offerings of any of these businesses or individuals, or the content made available by them. Hellomitr does not assume any responsibility or liability for the actions, products, and content of any of these and any other third-parties. The information displayed on Hellomitr is for informational purpose only, and does not amount to or be deemed to be an endorsement of any product or service under any circumstances.</p>
            <p className="l2">8.7. To the extent permitted by applicable law, Hellomitr disclaims any liability against any loss, damage, expenses, liabilities, claim, injury caused due to the failure of performance, omission, defect of products, or deletion, interruption, error, delay, virus, communication, unauthorised access, theft, destruction, alteration or use of records on Hellomitr.</p>
            <p className="l2">8.8. Hellomitr is not responsible for the content of any third party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to access links of any third party platforms, you are doing so entirely at your own risk and expense.</p>


            <h5>9. USER WARRANTIES AND RESTRICTIONS :</h5>
            <p className="l2">9.1. You represent and warrant that: (a) your use of Hellomitr and/or Services will not violate any applicable law or regulation; (b) all information that is submitted to Hellomitr in connection with Hellomitr and/or Services is true, accurate and lawful; (c) use of the content and material you supply does not breach any applicable Hellomitr policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory). If at any time, the information provided by you is found to be false or inaccurate, Hellomitr will have the right to reject registration, cancel all orders, and restrict you from using the Services and other affiliated services in the future without any prior intimation whatsoever. You agree to indemnify Hellomitr and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.</p>
            <p className="l2">9.2. You will use Hellomitr for lawful purposes only, and will not undertake any activity that is harmful to Hellomitr or its content or otherwise not envisaged through Hellomitr. You have a limited license to access and use Hellomitr, solely for the purpose of availing the Services, subject to these Terms of Use.</p>
            <p className="l2">9.3. The use of the Platform by you is restricted to personal use only, and you will not use any portion of Hellomitr (including the contents on the Platform) or Services for any resale or commercial purpose.</p>
            <p className="l2">9.4. You will not do any of the following:</p>
            <p className="l2">9.4.1. Delete or modify any content on Hellomitr, such as any information regarding the Services, their performance, sales or pricing;</p>
            <p className="l2">9.4.2. Use any engine, software, tool, agent or other mechanism (such as spiders, robots, avatars, worms, time bombs etc.) to navigate or search Hellomitr;</p>
            <p className="l2">9.4.3. Make false or malicious statements against the Services, Hellomitr or Hellomitr;</p>
            <p className="l2">9.4.4. Post, copy, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise disrupt or damage Hellomitr and/or Services or any connected network, or otherwise interfere with any person or entity's use or enjoyment of Hellomitr and/or the Services;</p>
            <p className="l2">9.4.5. Introduce any trojans, viruses, any other malicious software, and any bots or scrape Hellomitr for any information;</p>
            <p className="l2">9.4.6. Probe, scan, or test the vulnerability of any system, security or authentication measures implemented by us or otherwise tamper or attempt to tamper with our technological design and architecture;</p>
            <p className="l2">9.4.7. Hack into or introduce malicious software of any kind onto Hellomitr;</p>
            <p className="l2">9.4.8. Gain unauthorized access to, or interfere with, or damage, or disrupt the server on which the details connected to the Services are stored, or any other server, computer, or database connected to the Services; or</p>
            <p className="l2">9.4.9. Engage in any form of antisocial, disruptive, or destructive acts, including “flaming,” “spamming,” “flooding,” “trolling,”, “phishing” and “griefing” as those terms are commonly understood and used on the internet.</p>
            <p className="l2">9.5. You are prohibited from hosting, displaying, uploading, modifying, publishing, transmitting, updating or sharing on or through Hellomitr, any information that:</p>
            <p className="l2">9.5.1. belongs to another person and to which you do not have any right;</p>
            <p className="l2">9.5.2. is harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, invasive of another’s privacy, hateful, relating to or encouraging money laundering or gambling, or otherwise harmful in any manner whatsoever;</p>
            <p className="l2">9.5.3. Harms minors in any way;</p>
            <p className="l2">9.5.4. Infringes any patent, trademark, copyright or other proprietary rights;</p>
            <p className="l2">9.5.5. violates any law for the time being in force;</p>
            <p className="l2">9.5.6. Deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
            <p className="l2">9.5.7. Impersonates or defames another person; or</p>
            <p className="l2">9.5.8. Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.</p>

            <h5>10. INDEMNIFICATION AND LIMITATION OF LIABILITY:</h5>
            <p className="l2">10.1. You agree to indemnify, defend and hold harmless Hellomitr, its affiliates, officers, directors, employees, consultants, licensors, agents, and representatives from and against any and all third- party claims, losses, liabilities, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of Hellomitr or the Services, violation of these Terms of Use, or infringement of any intellectual property or other rights of Hellomitr or any third-party. Hellomitr will notify you promptly of any such claim, loss, liability, or demand, and in addition to the foregoing, you agree to provide Hellomitr with reasonable assistance, at their expense, in defending any such claim, loss, liability, damage, or cost.</p>
            <p className="l2">10.2. To the fullest extent permitted by law, in no event shall Hellomitr or any of its directors, officers, employees, agents or content or service providers (collectively, the “Hellomitr Representatives”) be liable to you for any direct, indirect, special, incidental, consequential, exemplary, special, remote or punitive damage, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses arising from, or directly or indirectly related to, the use of, or the inability to use, Hellomitr or the content, materials and functions related thereto, the Services, provision of information via Hellomitr, lost business, even if such Hellomitr Representatives have been advised of the possibility of such damages.</p>
            <p className="l2">10.3. In no event shall Hellomitr Representatives be liable for:</p>
            <p className="l2">10.3.1. The use or inability to use Hellomitr and/or the Services;</p>
            <p className="l2">10.3.2. Any content posted, transmitted, exchanged or received by or on behalf of any user or other person on or through Hellomitr;</p>
            <p className="l2">10.3.3. Any unauthorized access to or alteration of your transmissions of sensitive personal information or other user data; or</p>
            <p className="l2">10.3.4. Any other matter relating to Hellomitr or the Services.</p>
            <p className="l2">10.5. None of the directors, officials or employees of Hellomitr shall be personally liable for any action in connection with Hellomitr or the Services.</p>


            <h5>11. ACCESS OUTSIDE THE REPUBLIC OF INDIA:</h5>
            <p className="l2">11.1. Hellomitr makes no representation that the content on Hellomitr is appropriate to be used or accessed outside the Republic of India. Any users who use or access Hellomitr from outside the Republic of India, do so at their own risk and are responsible for compliance with the laws of such jurisdiction. These Terms of Use do not constitute, nor may these Terms of Use be used for or in connection with any promotional activities or solicitation by anyone in any jurisdiction in which such promotional activities or solicitation are not authorized or to any person to whom it is unlawful to promote or solicit.</p>

            <h5>12. TERM AND TERMINATION:</h5>
            <p className="l2">12.1. These Terms of Use shall be effective from the date of their publication on Hellomitr</p>
            <p className="l2">12.2. Hellomitr reserves the right to terminate the Services in the event of breach of any terms contained in these Terms of Use, misrepresentation of information, any unlawful activity by you or if Hellomitr is unable to verify or authenticate any information submitted by you.</p>
            <p className="l2">12.3. You may terminate these Terms of Use at any time, provided that you discontinue any further use of Hellomitr or Services. However, any such termination shall not cancel your obligation to pay for a product purchased on Hellomitr, or any other obligation which has accrued, or is unfulfilled and relates to the period, prior to termination.</p>

            <h5>13. FORCE MAJEURE:</h5>
            <p className="l2">13.1. Hellomitr will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond Hellomitr’s reasonable control.</p>


            <h5>14. WAIVER:</h5>
            <p className="l2">14.1. No provision in these Terms of Use will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by Hellomitr. Any consent by Hellomitr to, or waiver of your breach, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</p>

            <h5>15. SEVERABILITY:</h5>
            <p className="l2">15.1. If any provision of these Terms of Use is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision will be excluded from these Terms of Use and the remainder of these Terms of Use will be interpreted as if such provision were so excluded and will be enforceable in accordance with its terms; provided however that, in such event, these Terms of Use will be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction.</p>


            <h5>16. GRIEVANCE REDRESSAL:</h5>
            <p className="l2">16.1. You may submit any grievance with respect to Hellomitr or the Services, including with respect to any abuse on Hellomitr including any discrepancies or grievances with respect to access or usage of Hellomitr in violation of these Terms of Use by any person, to the Grievance Officer at:</p>
            <p className="l2">Name : <b>N Dinesh Rao</b></p>
            <p className="l2">E-mail ID : <b>ndineshrao@hellomitr.com</b></p>


            <h5>17. GOVERNING LAW AND DISPUTE RESOLUTION:</h5>
            <p className="l2">17.1. These Terms of Use, all transactions consummated between Hellomitr and you, and the relationship between Hellomitr and you is governed by the laws of India, without reference to any conflict of laws principles and with an exclusive jurisdiction to the courts of Bangalore (Urban).</p>

            <h5>18. AMENDMENT:</h5>
            <p className="l2">18.1. These Terms of Use are subject to amendments and modifications and may be updated from time to time, without any advance notice. You are requested to regularly review the Terms of Use as available on Hellomitr. You relationship with Hellomitr will be governed by the most current version of these Terms of Use, as published on Hellomitr.</p>

            <h5>19. MISCELLANEOUS:</h5>
            <p className="l2">19.1. In addition to these Terms of Use, you will also ensure that you are in compliance with the terms and conditions of the third parties, such as bank offers terms and conditions, brand promotional offers, whose links, if any, are contained/embedded in the Services. You agree that Hellomitr will not be liable for any transaction between itself and any such third parties.</p>
            <p className="l2">19.2. These Terms of Use supersede all previous oral and written terms and conditions (if any) communicated to you by Hellomitr, for the use of Hellomitr, and the rights and liabilities with respect to any Services to be provided by Hellomitr shall be limited to the scope of these Terms of Use.</p>


            <h5>20. NODAL OFFICER:</h5>
            <p className="l2">Name : <b>Parmod Madan</b></p>
            <p className="l2">Designation : <b>Nodal Officer</b></p>
            <p className="l2">E-mail ID : <b>parmod@hellomitr.com</b></p>

            <h5>TERMS AND CONDITIONS</h5>
            <p className="l2">The terms and conditions of sale as set out herein (“ Terms of Sale”) constitute an agreement between the person/ entity listed as seller (“we”, “us” or “our”) on the portal www.hellomitr.com and its corresponding mobile application (collectively, “Hellomitr”) and you (“ you” or “your”) and govern your purchase of the products (“Product(s)”) from us on or through Hellomitr. By placing an order for any Product with us or making a purchase of Product, you expressly agree to be bound by these Terms of Sale.</p>
            <p className="l2">These Terms of Sale are in addition to various agreements, Service Terms, Privacy Policy, Terms of Use and all other policies of Hellomitr. These Terms of Sale constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

            <h5>1. Our Contract</h5>
            <p className="l2">1.1. Listing and display of a Product by us on Hellomitr is our invitation to you to make an offer for purchase of such Product. Likewise, the placement of an order on Hellomitr by you is your offer to buy the Product(s) from us.</p>
            <p className="l2">1.2. Once you have placed an order with us for purchase of a Product, you will receive an e-mail confirming receipt of your order and containing the details of your order (the “Order Confirmation”). The Order Confirmation is merely an acknowledgement that we have received your order and does not signify our acceptance of your offer.</p>
            <p className="l2">1.3. We only accept your offer and conclude the contract of sale for a Product ordered by you, when the Product is shipped or dispatched to you and an e-mail confirmation is sent to you that the Product has been shipped or dispatched to you (the “Shipment Confirmation”). We reserve the right, at our sole discretion, to refuse or cancel any order for any reason whatsoever before sending Shipment Confirmation to you.</p>
            <p className="l2">1.4. You acknowledge that there may be certain Products in your order whose actual quantity may not be known at the time of order placement (for example, fruits, vegetables, etc.). Such Products will therefore be invoiced based on the exact weight at the time of packaging and upon dispatch, our Shipment Confirmation will reflect such marginal variance in the quantity of the Product as against your original order and relevant adjustment in the invoice amount.</p>
            <p className="l2">1.5. If your order is dispatched in more than one package, you may receive separate Shipment Confirmations for each package, and each Shipment Confirmation and corresponding dispatch will conclude a separate contract of sale between you and us for the Product(s) specified in that Shipment Confirmation.</p>
            <p className="l2">1.6. Your contract is with us and you confirm that the Product(s) ordered by you are purchased for your internal / personal purpose and not for re-sale or business purpose. Please note that we sell Products only in quantities which correspond to the usual requirements of an average household. This applies both to the number of Products ordered within a single order and the placing of several orders for the same Product where the individual orders comprise a quantity typical for a normal household.</p>
            <p className="l2">1.7. You can cancel your order for a Product at no cost at any time before we send the Shipment Confirmation relating to that Product.</p>
            <p className="l2">1.8. All orders placed on Hellomitr are subject to the availability of such Product, our acceptance of your offer as per the above and your continued adherence to these Terms of Sale.</p>


            <h5>2. Return and Refund</h5>
            <p className="l2">Please review the Returns Policy and Refund Policy of Hellomitr, which applies to Products sold by us.</p>


            <h5>3. Product Availability</h5>
            <p className="l2">We list availability information for the Products on the relevant webpage of Hellomitr. Beyond what we say on that webpage or otherwise on Hellomitr, we cannot be more specific about availability. Please note that dispatch estimates are just that. They are not guaranteed dispatch times and should not be relied upon as such. As we process your order, you will be informed by e-mail if any Products you order turn out to be unavailable or out of stock.</p>

            <h5>4. Product Pricing</h5>
            <p className="l2">4.1. All prices are listed in Indian Rupees. Price, as displayed, is inclusive of all applicable taxes.</p>
            <p className="l2">4.2. Products in your shopping cart of Hellomitr will reflect the most recent price as displayed on the Product’s information webpage on Hellomitr. Please note that this price may differ from the price shown for the Product when you first placed it in your shopping cart. Placing a Product in your shopping cart does not reserve the price shown at that time. It is also possible that a Product’s price may decrease between the time you place it in your shopping cart and the time you place the order.</p>
            <p className="l2">4.3. Subject to paragraph 1.4 above, the prices mentioned at the time of ordering will be the prices charged on the date of the delivery. Although prices of most of the Products do not fluctuate on a daily basis but prices of some of the Products (such as fresh food, vegetables, etc.) do change on a daily basis. In case the prices are higher or lower on the date of delivery, no additional charges will be collected or refunded, as the case may be, at the time of the delivery of the order, except as set out in paragraph 1.4 above.</p>
            
            <h5>5. Licenses</h5>
            <p className="l2">You acknowledge that there may be licenses/permissions required under the applicable laws to use, purchase or otherwise possess certain Product(s). You will be solely responsible for obtaining such licenses/permissions and complying with the terms of such licenses/permissions.</p>
            

            <h5>6. Taxes</h5>
            <p className="l2">You shall be responsible for payment of all fees/costs/charges associated with the purchase of Products from us and you agree to bear any and all applicable taxes.</p>

            <h5>7. Eligibility</h5>
            <p className="l2">Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e. persons who are 18 years of age or older, are of sound mind, and are not disqualified from entering into contracts by any law, can use Hellomitr and place an order with us. If you are a minor i.e. under the age of 18 years, you may purchase the Product on Hellomitr only with the involvement of a parent or guardian.</p>

            <h5>8. Limitation of Liability</h5>
            <p className="l2">In no event, our aggregate liability, if any, that is proven and ordered by a court of competent jurisdiction pursuant to a claim by you or person acting on your behalf, shall extend beyond the refund of money charged from you for purchases made pursuant to an order under which such liability has arisen and been established. We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when a contract for the sale of Product by us to you was formed.</p>

            <h5>9. Amendments</h5>
            <p className="l2">We reserve the right to make changes to our policies, and these Terms of Sale at any time. You will be subject to the policies and Terms of Sale in force at the time you order Product from us, unless any change to those policies or these Terms of Sale is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p>

            <h5>10. Force Majeure</h5>
            <p className="l2">We will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond our reasonable control.</p>

            <h5>11. Waiver</h5>
            <p className="l2">No provision in these Terms of Sale will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by us. Our consent to, or waiver of your breach, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</p>

            <h5>12. Governing Law and Dispute Resolution</h5>
            <p className="l2">These Terms of Sale, all transactions consummated between you and us, and our relationship with you is governed by the laws of India, without reference to any conflict of laws principles and with an exclusive jurisdiction to the courts of Bangalore (Urban).</p>

            <h5>13. Miscellaneous</h5>
            <p className="l2">13.1. In addition to these Terms of Sale, you will also ensure that you are in compliance with the terms and conditions of the third parties, such as bank offers terms and conditions, brand promotional offers, whose links, if any, are contained/embedded in the Service Terms or Terms of Use.</p>
            <p className="l2 mb-5">13.2. These Terms of Sale supersede all previous oral and written terms and conditions (if any) communicated to you by us, for the purchase of Product.</p>



        </div>

        <Footer/>
    </div>
  )
}

export default TermsAndConditions
